accounts/urls.py
from django.urls import path,include
from accounts import views

urlpatterns = [
    path('',views.registro, name='registro'),
    path('registro/sucesso' ,views.registro_sucesso, name='registro_sucesso'),
    path('ativar/<token>',views.user_active, name='user_active'),
    path('recuperar/',views.recupera_conta, name='recupera_conta'),
    path('recuperar/<id>/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}', views.create_new_password, name='create_new_password'),
    path('users_viewers', views.users_viewers_list,name='users_viewers_list'),
    path('inclui_vendedor',views.register_viewer,name='register_viewer'),
    path('inclui_vendedor/<int:pk>',views.edit_viewer,name='edit_viewer'),
    path('reset_password/<int:pk>',views.reset_password,name='reset_password'),
]

accounts/models.py
import re, random
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser,UserManager,PermissionsMixin
from django.conf import settings

class User(AbstractBaseUser,PermissionsMixin):

    username = models.CharField(
        'Usuário',max_length=50,unique=True,validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras e números '
                ,'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100,blank=True)
    email = models.EmailField('E-mail', unique=True)
    tel_user = models.CharField('Telefone', max_length=25,null=True,blank=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=False)
    is_masteruser = models.BooleanField('Usuario Master', default=True)
    date_joined = models.DateTimeField('Data de entrada', auto_now_add=True)
    img_user = models.ImageField('Imagem do perfil', blank=True, upload_to='images', null=True)
    # qtd_users = models.PositiveIntegerField('Usuarios',blank=True, null=True)
    user_master = models.ForeignKey('self',models.CASCADE,verbose_name='Usuario Master',blank=True,null=True)
    token = models.CharField('Token Senha', max_length=100, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        unique_together = [
            ('username', 'user_master','email')
        ]

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]



def pre_save_user(instance,**kwargs):
    if not instance.token:
        alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
        instance.token = ''.join(random.choice(alphabet) for i in range(100))



def post_save_user(instance,created,**kwargs):

    if created:
        if instance.is_masteruser is True:
            usuario = instance
            usuario.user_master = instance
            usuario.save()


            from templated_email import send_templated_mail
            send_templated_mail(
                template_name='email_ativa_conta.html',
                from_email='michel.carvalho22@gmail.com',
                recipient_list=[instance.email],
                context={
                    'domain': settings.SITE_DOMAIN,
                    'user' : instance
                },
            )



models.signals.pre_save.connect(pre_save_user,User)
models.signals.post_save.connect(post_save_user,User)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms

class UserCustomCreationForm(UserCreationForm):
    # aceite = forms.BooleanField( required=False)
    #
    # def clean_aceite(self):
    #     aceite = self.cleaned_data.get('aceite', False)
    #
    #     if not aceite:
    #         raise forms.ValidationError('Você deve aceitar os termos de uso e privacidade para concluir seu cadastro')
    #     return aceite

    def __init__(self,  *args, **kwargs):
        super(UserCustomCreationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ['username','name','email']


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','name','email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username','email','name','is_active','is_staff','is_superuser']



class ForgotPasswordForm(forms.Form):

    email = forms.EmailField(label='E-mail')





class UserViewerCreationForm(UserCreationForm):


    class Meta:
        model = User
        fields = ['username','name','email','tel_user']

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView,UpdateView
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.decorators import login_required
from .forms import ForgotPasswordForm
from django.contrib import messages
from django.http import HttpResponse,Http404
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.conf import settings


from .models import User
from .forms import UserCustomCreationForm,UserViewerCreationForm


class RegistraUsuario(CreateView):

    model = User
    template_name = 'registro.html'
    form_class = UserCustomCreationForm
    success_url = reverse_lazy('registro_sucesso')

registro = RegistraUsuario.as_view()


def user_active(request, token):
    user = User.objects.get(token=token)
    user.is_active = True
    # if user.is_masteruser is True:
        # user.user_master = user.pk
    user.save()

    return redirect('login')

def recupera_conta(request):
    form = ForgotPasswordForm(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data['email']
        try:
            user = User.objects.get(email=email)
        except:
            user = None
        if user:
            token = default_token_generator.make_token(user)
            from templated_email import send_templated_mail
            send_templated_mail(
                template_name='email_recupera_conta',
                from_email='michel.carvalho22@gmail.com',
                recipient_list=[user.email],
                context = {
                    'domain' : settings.SITE_DOMAIN,
                    'user' : user,
                    'token' : token
                },


            )

            return render(request,template_name='recupera_info.html')

    context = {
        'form' : form
    }

    return render(request,'recupera_conta.html',context)









def reset_password(request,pk):
    form = ForgotPasswordForm(request.POST or None)
    user = User.objects.get(pk=pk)
    if user:
       token = default_token_generator.make_token(user)
       from templated_email import send_templated_mail
       send_templated_mail(
          template_name='email_recupera_conta',
          from_email='michel.carvalho22@gmail.com',
          recipient_list=[user.email],
          context = {
         'domain' : settings.SITE_DOMAIN,
         'user' : user,
         'token' : token
         },


       )
       messages.success(request, 'Solicitação realizada. Em breve o usuário receberá um e-mail com a nova senha')
       return redirect('users_viewers_list')

    context = {
        'form' : form
    }

    return render(request,'recover_account.html',context)



def registro_sucesso(request):

    return render(request,'sucesso_conta.html')




def create_new_password(request,id,token):
    user = User.objects.get(id=id)
    if default_token_generator.check_token(user,token):
        form = SetPasswordForm(user,request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('login')
        context = {
            'form' : form
         }
        return render(request,'nova_senha.html', context)

    raise Http404


@login_required
def users_viewers_list(request):

    if request.is_ajax():
        template_name = '_table_users_viewers.html'
    else:
        template_name = 'users_viewers_list.html'


    users_viewers = User.objects.filter(user_master=request.user,is_masteruser=False)


    context = {
        'dominio' : settings.SITE_DOMAIN,
        'users_viewers' : users_viewers,
    }
    return render(request,template_name,context)



class RegisterUserViewer(LoginRequiredMixin, CreateView):


        def get_template_names(self):
            if self.request.is_ajax():
                return ["_create_viewer.html"]
            else:
                raise Http404

        def get_success_url(self):
            return reverse_lazy('users_viewers_list')

        model = User
        form_class = UserViewerCreationForm

        def form_valid(self, form):
            userv = form.save(commit=False)
            userv.user_master = self.request.user.user_master
            userv.is_masteruser = False
            userv.is_active = True
            userv.save()

            if self.request.is_ajax():
                context = self.get_context_data(form=form, ok='ok', success=True)
                return self.render_to_response(context)
            else:
                return redirect(self.get_success_url())


register_viewer = RegisterUserViewer.as_view()



class EditUserViewer(LoginRequiredMixin,UpdateView):

    def get_template_names(self):
        if self.request.is_ajax():
            return ["_alter_viewer.html"]
        else:
           raise Http404

    model = User
    fields = ['name','email','is_active','tel_user']

    def get_success_url(self):
        return reverse_lazy('users_viewers_list')

    def form_valid(self,form):
        form.save()

        if self.request.is_ajax():
            context = self.get_context_data(form=form,success=True)
            return self.render_to_response(context)
        else:
            return redirect(self.get_success_url())

edit_viewer = EditUserViewer.as_view()

accounts/templates/_alter_viewer.html
{% load static widget_tweaks %}
{% if success %}
<script>
	   close_modal=true;
</script>
{% endif %}
<form action="{% url 'edit_viewer' object.pk %}" enctype="multipart/form-data" class="edit_vendedor"
      method="post" onsubmit="return false;">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
       <div class="alert bg-red">
           {{ error }}
       </div>
    {% endfor %}
    <div class="row clearfix">
        <div class="col-md-6">
            <label for="{{ form.name.id }}">Nome</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.name class='form-control' placeholder='Informe o Nome' %}
                </div>
                {% for error in form.name.errors  %}
               <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            <label for="{{ form.tel_user.id }}">Celular</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.tel_user class='form-control' placeholder='Nº Celular (com DDD)' %}
                </div>
                {% for error in form.tel_user.errors  %}
                <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-12">
            <label for="{{ form.email.id }}">Email</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.email class='form-control' placeholder='Informe o endereço de email' %}
                </div>
                {% for error in form.email.errors  %}
                <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-12">
            {% render_field form.is_active type="checkbox" class='chk-col-amber' %}
            <label for="id_is_active">Ativo</label>
        </div>
    </div>

    <button type="submit" class="btn bg-orange m-t-15 waves-effect">SALVAR</button>
</form>

accounts/templates/_create_viewer.html
{% load static widget_tweaks %}
{% if success %}
<script>
	   close_modal=true;
</script>
{% endif %}
<form action="" class="create_vendedor" method="post" onsubmit="return false;">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
       <div class="alert bg-red">
           {{ error }}
       </div>
    {% endfor %}
    <div class="row clearfix">
        <div class="col-md-6">
            <label for="{{ form.name.id }}">Nome</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.name class='form-control' placeholder='Informe o Nome' %}
                </div>
                {% for error in form.name.errors  %}
                <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            <label for="{{ form.username.id }}">Usuário</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.username class='form-control' placeholder='Informe o Usuario de Login' %}
                </div>
                {% for error in form.username.errors  %}
                <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <label for="{{ form.email.id }}">Email</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.email class='form-control' placeholder='Informe o endereço de email' %}
                </div>
                {% for error in form.email.errors  %}
                <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4">
            <label for="{{ form.tel_user.id }}">Celular</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.tel_user class='form-control' placeholder='Nº Celular (com DDD)' %}
                </div>
                {% for error in form.tel_user.errors  %}
                <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            <label for="{{ form.password1.id }}">Senha</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.password1 class='form-control' placeholder='Senha' %}
                </div>
                {% for error in form.password1.errors  %}
               <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            <label for="{{ form.password2.id }}">Senha</label>
            <div class="form-group">
                <div class="form-line">
                    {% render_field form.password2 class='form-control' placeholder='Confirmação de Senha' %}
                </div>
                {% for error in form.password2.errors  %}
               <label class="error">
                   {{ error }}
                </label>
                {% endfor %}
            </div>
        </div>
    </div>

    <button type="submit" class="btn bg-pink m-t-15 waves-effect">SALVAR</button>
</form>

accounts/templates/_table_users_viewers.html
<table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="tabela_users_viewers">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Nº Telefone</th>
            <th>Situação</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for users in users_viewers %}
        <tr>
            <td>{{ users.name }}</td>
            <td>{{ users.email }}</td>
            <td>{% if users.tel_user%} {{ users.tel_user }} {% endif %}</td>
            <td>
                {% if users.is_active == True %}
                <span class="label label bg-green">Ativo</span>
                {% else %}
                <span class="label bg-red">Inativo</span>
                {% endif %}
            </td>
            <td>

                <button type="button" class="btn btn-xs btn-warning waves-effect edit_registro"
                        data-toggle="tooltip" data-placement="bottom" title="Editar Registro"
                        href="{% url 'edit_viewer' users.pk %}">
                     <i class="material-icons">mode_edit</i>
                </button>
                <a type="button" class="btn btn-xs  bg-deep-orange waves-effect"
                        data-toggle="tooltip" data-placement="bottom" title="Atualizar senha de acesso"
                        href="{% url 'reset_password' users.pk %}">
                     <i class="material-icons">refresh</i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

accounts/templates/login.html
{% load static widget_tweaks %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Prospectando - Alcance sua Meta | LOGIN </title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static 'assets/plugins/node-waves/waves.css' %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static 'assets/plugins/animate-css/animate.css' %}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body class="login-page">
    <div class="login-box">
        <div class="logo">
            <center>
                <img src="{% static 'assets/images/logo_login.png' %}">
            </center>
             <small>Alcançe sua meta!</small>

        </div>
        <div class="card">
            <div class="body">
                <form id="sign_in" method="POST">
                    {% csrf_token %}
                     {% for error in form.non_field_errors %}
                     <label class="error">
                        {{ error }}
                     </label>
                     {% endfor %}
                    <div class="msg">Favor informar seus dados para começar</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            {% render_field form.username class='form-control' placeholder='Usuário' %}
                            {% for error in form.username.errors %}
                            <label class="error">
                               {{ error }}
                             </label>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            {% render_field form.password class='form-control' placeholder='Senha' %}
                            {% for error in form.password.errors %}
                            <label class="error">
                                {{ error }}
                            </label>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <button class="btn btn-block bg-pink waves-effect" type="submit">ACESSAR</button>
                        </div>
                    </div>
                    <div class="row m-t-15 m-b--20">
                        <div class="col-xs-6">
                            <a href="{% url 'registro' %}">Criar conta!</a>
                        </div>
                        <div class="col-xs-6 align-right">
                            <a href="{% url 'recupera_conta' %}">Perdeu sua senha?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static 'assets/plugins/node-waves/waves.js' %}"></script>

    <!-- Validation Plugin Js -->
    <script src="{% static 'assets/plugins/jquery-validation/jquery.validate.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'assets/js/admin.js' %}"></script>
    <script src="{% static 'assets/js/pages/examples/sign-in.js' %}"></script>
</body>

</html>

accounts/templates/nova_senha.html
{% load static widget_tweaks %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Prospectando - Alcance sua Meta | RECUPERAR CONTA </title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static 'assets/plugins/node-waves/waves.css' %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static 'assets/plugins/animate-css/animate.css' %}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body class="login-page">
    <div class="login-box">
        <div class="logo">
            <a href="javascript:void(0);">Admin<b>BSB</b></a>
            <small>Admin BootStrap Based - Material Design</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="sign_in" method="POST">
                    {% csrf_token %}
                     {% for error in form.non_field_errors %}
                     <div class="alert bg-red">
                        {{ error }}
                     </div>
                     {% endfor %}
                    <div class="msg">Atualizar Senha</div>
                    {% for field in form %}
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            {% render_field field class='form-control' placeholder=field.label %}
                            {% for error in form.field.errors %}
                           <label class="error">
                              {{ error }}
                           </label>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="row">
                        <div class="col-xs-6">
                            <button class="btn btn-block bg-pink waves-effect" type="submit">ATUALIZAR SENHA</button>
                        </div>
                    </div>
                    <div class="row m-t-15 m-b--20">
                        <div class="col-xs-6">
                            <a href="{% url 'registro' %}">Criar conta!</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static 'assets/plugins/node-waves/waves.js' %}"></script>

    <!-- Validation Plugin Js -->
    <script src="{% static 'assets/plugins/jquery-validation/jquery.validate.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'assets/js/admin.js' %}"></script>
    <script src="{% static 'assets/js/pages/examples/sign-in.js' %}"></script>
</body>

</html>

accounts/templates/recupera_conta.html
{% load static widget_tweaks %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Prospectando - Alcance sua Meta | RECUPERA CONTA </title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static 'assets/plugins/node-waves/waves.css' %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static 'assets/plugins/animate-css/animate.css' %}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body class="login-page">
    <div class="login-box">
        <div class="logo">
          <center>
                <img src="{% static 'assets/images/logo_login.png' %}">
            </center>
             <small>Alcançe sua meta!</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="sign_in" method="POST">
                    {% csrf_token %}
                     {% for error in form.non_field_errors %}
                     <div class="alert bg-red">
                        {{ error }}
                     </div>
                     {% endfor %}
                    <div class="msg">Para resgatar sua conta, favor informe seu e-mail</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">email</i>
                        </span>
                        <div class="form-line">
                            {% render_field form.email class='form-control' placeholder='Email' %}
                            {% for error in form.email.errors %}
                            <label class="error">
                                {{ error }}
                            </label>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6">
                            <button class="btn btn-block bg-pink waves-effect" type="submit">RECUPERAR CONTA</button>
                        </div>
                    </div>
                    <div class="row m-t-15 m-b--20">
                        <div class="col-xs-6">
                            <a href="{% url 'registro' %}">Criar conta!</a>
                        </div>
                        <div class="col-xs-6 align-right">
                            <a href="{% url 'login' %}">Login</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static 'assets/plugins/node-waves/waves.js' %}"></script>

    <!-- Validation Plugin Js -->
    <script src="{% static 'assets/plugins/jquery-validation/jquery.validate.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'assets/js/admin.js' %}"></script>
    <script src="{% static 'assets/js/pages/examples/sign-in.js' %}"></script>
</body>

</html>