accounts/urls.py
from django.urls import path,include
from accounts import views

urlpatterns = [
    path('',views.registro, name='registro'),
    path('registro/sucesso' ,views.registro_sucesso, name='registro_sucesso'),
    path('ativar/<token>',views.user_active, name='user_active'),
    path('recuperar/',views.recupera_conta, name='recupera_conta'),
    path('recuperar/<id>/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}', views.create_new_password, name='create_new_password'),
    path('users_viewers', views.users_viewers_list,name='users_viewers_list'),
    path('inclui_vendedor',views.register_viewer,name='register_viewer'),
    path('inclui_vendedor/<int:pk>',views.edit_viewer,name='edit_viewer'),
    path('reset_password/<int:pk>',views.reset_password,name='reset_password'),
]

cadastros/models.py
from django.db import models

# Create your models here.


class Lead(models.Model):

    # informação do dono da conta (usuario Master)
    master_user = models.ForeignKey('accounts.User',models.CASCADE,verbose_name='Usuário Master')

    # dados principais
    cnpj_cpf = models.CharField('CNPJ/CPF',max_length=20, null=True,blank=True)
    razao = models.CharField('Razão/Nome', max_length=60)
    fantasia = models.CharField('Fantasia', max_length=40, blank=True,null=True)

    # endereço
    cep = models.CharField('CEP', max_length=12, blank=True, null=True)
    endereco = models.CharField('Endereço',max_length=50,blank=True,null=True)
    numero = models.CharField('Nº',max_length=10, blank=True,null=True)
    complemento = models.CharField('Complemento', max_length=30,blank=True,null=True)
    bairro = models.CharField('Bairro', max_length=40, blank=True, null=True)
    cidade = models.CharField('Cidade', max_length=30, blank=True, null=True)
    uf = models.CharField('UF', max_length=2, blank=True, null=True)

    # dados contato
    email = models.EmailField('Email',max_length=100)
    telefone = models.CharField('Telefone',max_length=20)

    # outros dados
    data_cadastro = models.DateTimeField('Data de cadastro', auto_now_add=True,blank=True,null=True)
    situacao = models.BooleanField('Ativo',default=True)


    class Meta:
        verbose_name = 'Lead'
        verbose_name_plural = 'Leads'
        unique_together = [
           ('master_user', 'cnpj_cpf')
        ]

    def __str__(self):
        return self.razao


class StatusProspeccao(models.Model):

    master_user = models.ForeignKey('accounts.User', models.CASCADE, verbose_name='Usuário Master')

    status_desc = models.CharField('Descrição',max_length=40)
    intervalo = models.IntegerField('Intervalo de retorno (dias)')


    class Meta:
        verbose_name = 'Status Prospecção'
        unique_together = [
            ('master_user', 'status_desc')
        ]


    def __str__(self):
        return self.status_desc


class FluxoProspeccao(models.Model):


    master_user = models.ForeignKey('accounts.User', models.CASCADE, verbose_name='Usuário Master')

    desc_fluxo = models.CharField('Descrição do Fluxo',max_length=60)
    qtd_passos = models.IntegerField('Quantidade Passos')


    passo1 = models.ForeignKey('cadastros.StatusProspeccao',models.CASCADE,verbose_name='Passo1',
                               related_name='passo1' ,null=True, blank=True)
    qtd_contatos1 = models.IntegerField('Quantidade Contatos',default=0)
    passo_falha1 = models.ForeignKey('cadastros.StatusProspeccao', models.CASCADE,
                               verbose_name='Próximo Passo - Falha', related_name='passo_falha1',
                               null=True, blank=True)


    passo2 = models.ForeignKey('cadastros.StatusProspeccao', models.CASCADE, verbose_name='Passo2',
                               related_name='passo2',null=True, blank=True)
    qtd_contatos2 = models.IntegerField('Quantidade Contatos',default=0)
    passo_falha2 = models.ForeignKey('cadastros.StatusProspeccao', models.CASCADE,
                                     verbose_name='Próximo Passo - Falha', related_name='passo_falha2',
                                     null = True, blank = True)


    passo3 = models.ForeignKey('cadastros.StatusProspeccao', models.CASCADE, verbose_name='Passo3',
                               related_name='passo3',null = True, blank = True)
    qtd_contatos3 = models.IntegerField('Quantidade Contatos',default=0)
    passo_falha3 = models.ForeignKey('cadastros.StatusProspeccao', models.CASCADE,
                                     verbose_name='Próximo Passo - Falha', related_name='passo_falha3',
                                     null=True, blank=True)


    class Meta:
        verbose_name = 'Fluxo Prospecção'
        unique_together = [
            ('master_user','desc_fluxo')
        ]

    def __str__(self):
        return self.desc_fluxo

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect

# Create your views here.


def view_success_data(request,view,frase):

    messages.success(request, frase)
    return redirect(view)


def view_success(request):
  pass

core/templates/base.html
{% load static widget_tweaks  %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Portal Lojas - Alcance sua Meta </title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/node-waves/waves.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/animate-css/animate.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <link href="{% static 'assets/plugins/sweetalert/sweetalert.css' %} " rel="stylesheet" />


    <link href="{% static 'assets/css/themes/all-themes.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css' %}" rel="stylesheet">


</head>

<body class="theme-red">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Carregando...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="{% url 'principal' %}">PROSPECTANDO</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!-- Call Search -->
                    <!--<li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>-->
                    <!-- #END# Call Search -->
                    <!-- Notifications -->
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            <i class="material-icons">notifications</i>
                            <span class="label-count">2</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">NOTIFICATIONS</li>
                            <li class="body">
                                <ul class="menu">
                                    <li>
                                        <a href="javascript:void(0);">
                                            <div class="icon-circle bg-light-green">
                                                <i class="material-icons">person_add</i>
                                            </div>
                                            <div class="menu-info">
                                                <h4>12 new members joined</h4>
                                                <p>
                                                    <i class="material-icons">access_time</i> 14 mins ago
                                                </p>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="javascript:void(0);">View All Notifications</a>
                            </li>
                        </ul>
                    </li>
                    <!-- #END# Notifications -->
                    <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons"></i></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Menu Lateral -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="images/user.png" width="48" height="48" alt="User" />
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">John Doe</div>
                    <div class="email">john.doe@example.com</div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:void(0);"><i class="material-icons">person</i>Profile</a></li>
                            <li role="seperator" class="divider"></li>
                            <li><a href="javascript:void(0);"><i class="material-icons">group</i>Followers</a></li>
                            <li><a href="javascript:void(0);"><i class="material-icons">shopping_cart</i>Sales</a></li>
                            <li><a href="javascript:void(0);"><i class="material-icons">favorite</i>Likes</a></li>
                            <li role="seperator" class="divider"></li>
                            <li><a href="javascript:void(0);"><i class="material-icons">input</i>Sign Out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="active">
                        <a href="{% url 'principal' %}">
                            <i class="material-icons">home</i>
                            <span>Principal</span>
                        </a>
                    </li>
                    <a href="javascript:void(0);" class="menu-toggle  work " >
                        <i class="material-icons">settings</i>
                        <span>Configurações Workflow</span>
                     </a>
                    <ul class="ml-menu work1">
                        <li class="work2">
                          <a class="status_prosp" href="{% url 'status_lista' %}">Status de Folow Up</a>
                          <a class="fluxo" href="{% url 'fluxo_lista' %}">Fluxo de Workflow</a>
                        </li>
                    </ul>
                     <a href="javascript:void(0);" class="menu-toggle  cadastros " >
                        <i class="material-icons">storage</i>
                        <span>Cadastros</span>
                     </a>
                    <ul class="ml-menu cadastros1">
                        <li class="cadastros2">
                          <a class="vendedores" href="{% url 'users_viewers_list' %}">Vendedores</a>
                          <a class="leads" href="{% url 'leads_lista' %}">Leads/Prospects</a>
                        </li>
                    </ul>
                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2018 <a href="javascript:void(0);">   Prospectando</a>.
                </div>
                <div class="version">
                    <b>Versão: </b> 1.0.0
                </div>
            </div>
            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->
    </section>

    <section class="content">
        <div class="container-fluid">
           <div class="container-fluid">
                <div class="block-header">
                    <h2>{% block title %} {% endblock %} </h2>

                </div>
               {% block page_body %} {% endblock %}
            </div>


        </div>
    </section>


    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-select/js/bootstrap-select.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-slimscroll/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'assets/plugins/node-waves/waves.js' %}"></script>
    <script src="{% static 'assets/js/admin.js' %}"></script>
    <script src="{% static 'assets/js/demo.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-datatable/jquery.dataTables.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'assets/js/pages/ui/tooltips-popovers.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-notify/bootstrap-notify.js' %}"></script>
    <script src="{% static 'assets/plugins/sweetalert/sweetalert.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>



    <script>
        $(document).ready(function() {
             {% block javascript %}
             {% endblock %}
        });
    </script>



</body>

</html>

core/templates/js_mask_telefone.html
$(".telefone").focusout(function() {
    var phone, element;
    element = $(this);
    element.unmask();
    phone = element.val().replace(/\D/g, '');
    if (phone.length > 10) {
        element.mask("(99) 99999-9999");
    } else {
        element.mask("(99) 9999-9999?9");
    }
}).trigger('focusout');

core/templates/js_pesquisas_cnpj_cep.html
<!--CEP-->

                      function limpa_formulário_cep() {
                        // Limpa valores do formulário de cep.
                        $("#id_endereco").val("");
                        $("#id_bairro").val("");
                        $("#id_cidade").val("");
                        $("#id_uf").val("");
                      }

                      $("#id_cep").blur(function() {

                        //Nova variável "cep" somente com dígitos.

                        var cep = $(this).val().replace(/\D/g, '');

                        //Verifica se campo cep possui valor informado.
                        if (cep != "") {

                            //Expressão regular para validar o CEP.
                            var validacep = /^[0-9]{8}$/;

                            //Valida o formato do CEP.
                            if(validacep.test(cep)) {
                                $(".ret_cep").addClass('open');
                                //Preenche os campos com "..." enquanto consulta webservice.
                                $("#id_endereco").val("...");
                                $("#id_bairro").val("...");
                                $("#id_cidade").val("...");
                                $("#id_uf").val("...");

                                //Consulta o webservice viacep.com.br/
                                $.getJSON("//viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                                    if (!("erro" in dados)) {
                                        //Atualiza os campos com os valores da consulta.
                                        $("#id_endereco").val(dados.logradouro);
                                        $("#id_bairro").val(dados.bairro);
                                        $("#id_cidade").val(dados.localidade);
                                        $("#id_uf").val(dados.uf);
                                        var ibge = dados.ibge;
                                        var ibge_uf = ibge.substring(0, 2);
                                        var ibge_mun = ibge.substring(2,8);
                                        $("#id_ibge_uf").val(ibge_uf);
                                        $("#id_ibge_mun").val(ibge_mun);


                                    } //end if.
                                    else {
                                        //CEP pesquisado não foi encontrado.
                                        limpa_formulário_cep();
                                        alert("CEP não encontrado.");
                                    }
                                });
                            } //end if.
                            else {
                                //cep é inválido.
                                limpa_formulário_cep();
                                alert("Formato de CEP inválido.");
                            }
                        } //end if.
                        else {
                            //cep sem valor, limpa formulário.
                            limpa_formulário_cep();
                        }
                      });
<!--FIM CEP-->

<!--CNPJ-->
$("#id_cnpj_cpf").blur(function(){
     if($(this).val().length > 13){
            function limpa_formulario_cadastro(){
                   $("#id_cnpj_cpf").val("");
                   $("#id_razao").val("");
                   $("#id_fantasia").val("");
                   $("#id_cep").val("");
                   $("#id_endereco").val("");
                   $("#id_numero").val("");
                   $("#id_complemento").val("");
                   $("#id_bairro").val("");
                   $("#id_uf").val("");
            }

            var cnpj = $("#id_cnpj_cpf").val().replace(/\D/g, '');

            if (cnpj != "") {
                    $("#id_razao").val("...");
                    $(".retorno_busca").addClass('open');
                    $("#id_fantasia").val("...");
                    $("#id_cep").val("...");
                    $("#id_endereco").val("...");
                    $("#id_numero").val("...");
                    $("#id_cidade").val("...");
                    $("#id_complemento").val("...");
                    $("#id_bairro").val("...");
                    $("#id_uf").val("...");
            }

            $.getJSON("//www.receitaws.com.br/v1/cnpj/"+cnpj+'/?callback=?', function(dados) {
            var checkcnpj = dados.cnpj
                                if(checkcnpj != undefined){
                                           //Atualiza os campos com os valores da consulta.
                                        $("#id_razao").val(dados.nome);
                                        $("#id_fantasia").val(dados.fantasia);
                                        $("#id_cep").val(dados.cep);
                                        $("#id_endereco").val(dados.logradouro);
                                        $("#id_numero").val(dados.numero);
                                        $("#id_cidade").val(dados.municipio);
                                        $("#id_complemento").val(dados.complemento);
                                        $("#id_bairro").val(dados.bairro);
                                        $("#id_uf").val(dados.uf);
                                }
                                else {
                                    limpa_formulario_cadastro();
                                    alert("CNPJ Inválido");
                                }

            });
     }
});


<!--FIM CNPJ-->